# Generated by Django 4.2.7 on 2024-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbot',
            name='custom_task',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
